Implementação GCI
gcinterceptor/msgpush-nodejs pull request #8
Opened 2018-10-14 02:23 UTC by emersoncantalice

Implementation GCI Node.Js
Create tests descriotion with GCI

2018-10-14 14:38 UTC, danielfireman requested changes
Muito bacana! Favor endereçar os pedidos abaixo!

2018-10-14 14:38 UTC, danielfireman commented on gcinterceptor.js
> +                res.status(200).send(v8.getHeapSpaceStatistics().filter(function (ns) {
Tive problemas em ler essa linha, poderia quebrar ou refatorar, por favor?

2018-10-14 14:38 UTC, danielfireman commented on experiments/config_stateful.toml
> +    start = 'for ip in $ip1 $ip2 $ip3 $ip4; do ssh -i ${sshkey} ubuntu@${ip} "PORT=3001 MSG_SIZE=20480 WINDOW_SIZE=128 NODE_ENV=production node --max_old_space_size=4096 --trace_gc_verbose -trace_gc
Você confirmou se max_old_space_size é em MB?

2018-10-14 14:38 UTC, danielfireman commented on experiments/config_stateful.toml
> +    start = 'for ip in $ip1 $ip2 $ip3 $ip4; do ssh -i ${sshkey} ubuntu@${ip} "PORT=3002 USE_GCI=TRUE MSG_SIZE=20480 WINDOW_SIZE=128 NODE_ENV=production node --expose-gc --max_old_space_size=4096 --tr
O tamanho do heap está o mesmo.

2018-10-14 14:38 UTC, danielfireman commented on experiments/config_stateful.toml
> +    start = 'for ip in $ip1 $ip2 $ip3 $ip4; do ssh -i ${sshkey} ubuntu@${ip} "PORT=3002 USE_GCI=TRUE MSG_SIZE=20480 WINDOW_SIZE=128 NODE_ENV=production node --expose-gc --max_old_space_size=4096 --tr
Lembrar de corrigir em no_gci e gci.

2018-10-15 02:08 UTC, emersoncantalice commented on experiments/config_stateful.toml
> +    start = 'for ip in $ip1 $ip2 $ip3 $ip4; do ssh -i ${sshkey} ubuntu@${ip} "PORT=3001 MSG_SIZE=20480 WINDOW_SIZE=128 NODE_ENV=production node --max_old_space_size=4096 --trace_gc_verbose -trace_gc
Sim, a documentação não ajuda muito, mas todas as ocorrecias de uso estão em MB e o código também https://github.com/nodejs/node/blob/ec02b811a8a5c999bab4de312be2d732b7d9d50b/deps/v8/src/heap/heap.cc#L82

2018-10-15 02:35 UTC, merged